version: '3.6'
services:
  iris:
    build:
      context: ./
      dockerfile : Dockerfile
      args:
        - IRIS_PASSWORD=${IRIS_PASSWORD:-SYS}
    volumes:
      - ./:/irisdev/app/
    ports:
    - 52775:52773
    - 51776:1972
    - 4040:8080
    - 8888:8888
    command: -a "sh /opt/irisapp/server_start.sh"